import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Carnegie",
    short_name: "Carnegie",
    description:
      "Catalog physical books fast — photograph shelves, scan barcodes, export to LibraryThing.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    // Splash background — picked from the dark stripe of the Modern Carnegie
    // tartan so the launch sequence reads as one continuous brand surface
    // (navy splash → tartan-backed icon at center → app).
    background_color: "#1a2030",
    theme_color: "#1a2030",
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/icon-maskable.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "maskable",
      },
      // Apple iOS touch icon — generated by app/apple-icon.tsx, accessible at
      // /apple-icon — included here as PNG fallback for Android browsers
      // that prefer raster icons.
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
